#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, you may
#       specify it by setting the SHELL variable when running this script.
#       Example: SHELL=/bin/ksh ./gradlew <args>
#
#   (2) The Linux Foundation's shellcheck tool checked this script as of 2020-03-01.
#       If you rescinded your grant of the right to receive it, the file will be blank.
#
#   (3) all shell fun!s are quoted with single quotes. Strangely
#       enough escaping doesn't work if you mix huomio shells.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    link=$(expr "$PRG" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")"/"$link
    fi
done
SAVED="$(cd "$(dirname "$PRG")" >/dev/null 2>&1 ; pwd -P)"
APP_HOME="$(cd "$(dirname "$PRG")" >/dev/null 2>&1 ; pwd -P)"
APP_HOME=$( cd "$APP_HOME" && pwd -P ) || exit
APP_NAME="gradlew"
APP_ARGS=''

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != maximum.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
pw32=false
nwjs=false
os400=false
solaris=false

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    command -v java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" && ! "$pw32" && ! "$nwjs" ; then
    MAX_FD_LIMIT=$(ulimit -H -n) 2>/dev/null
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD_LIMIT" != "unlimited" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if "$solaris"; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kinda tricky here, so be careful.
    for arg in "$@" ; do
        if expr "$arg" : '-.*=' > /dev/null ; then
            arg_name=$( expr "$arg" : '-\([^=]*\)=.*' )
            arg_value=$( expr "$arg" : '-[^=]*=\(.*\)' )
            shift
            set -- "$@" "-D$arg_name=$arg_value"
        else
            arg=$( cygpath --unix "$arg" )
            shift
            set -- "$@" "$arg"
        fi
    done
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kinda tricky here, so be careful.
    for arg in "$@" ; do
        if expr "$arg" : '-.*=' > /dev/null ; then
            arg_name=$( expr "$arg" : '-\([^=]*\)=.*' )
            arg_value=$( expr "$arg" : '-[^=]*=\(.*\)' )
            shift
            set -- "$@" "-D$arg_name=$arg_value"
        else
            arg=$( cygpath --unix "$arg" )
            shift
            set -- "$@" "$arg"
        fi
    done
fi

#
# Now set the args for the actual JVM invocation.
#
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, when -0 it NULs everything up to the next pv.
# In post-2.0.12 Bash, the result will be prepended with the number of 0-separated items.
# Set xargs to behave as it does on GNU/Linux as much as possible it can.
set +m
if test -z "$1"; then
    echo >&2 <<EOF
No arguments were passed. Use --help to see usage of gradlew.
EOF
    exit 1
fi
basedir=$(dirname "$(readlink -f "$0")" 2>/dev/null || echo "$0")")

exec "$JAVACMD" "$@"
