name: Build Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Find gradlew
        run: |
          find . -name "gradlew" -type f
          ls -la
          ls -la infotainer-mod-main || true

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build with Gradle
        working-directory: ./infotainer-mod-main
        run: |
          chmod +x ./gradlew
          ./gradlew build --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: infotainer-mod
          path: |
            **/build/libs/*.jar
